/**
 * Application Constants and Standard Status Codes
 */

const ERROR_CODES = {
  INVALID_URL: 'INVALID_URL',
  UNSUPPORTED_URL: 'UNSUPPORTED_URL',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MALFORMED_JSON: 'MALFORMED_JSON',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_NOT_ACCESSIBLE: 'PROFILE_NOT_ACCESSIBLE',
  PROFILE_RESTRICTED: 'PROFILE_RESTRICTED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UPSTREAM_RATE_LIMITED: 'UPSTREAM_RATE_LIMITED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  EXTRACTION_FAILED: 'EXTRACTION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  GATEWAY_TIMEOUT: 504
};

const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0'
];

module.exports = {
  ERROR_CODES,
  HTTP_STATUS,
  USER_AGENTS
};
